export const MOCK_CUSTOMERS = [
    {
        sqn: '101',
        name: 'Ahmed Mohamed',
        phone: '615000001',
        balance: 15.5,
        prevBalance: 5.0,
        total: 20.5,
        fahfahin: 'Balan',
        date: '2023-12-25',
        status: 'Pending',
        type: 'Normal',
        issue: 'Process',
        kwt: 120,
        note: 'Call later',
    },
    {
        sqn: '102',
        name: 'Fatima Ali',
        phone: '615000002',
        balance: 0.0,
        prevBalance: 0.0,
        total: 0.0,
        fahfahin: 'Ok',
        date: '2023-12-20',
        status: 'Paid',
        type: 'Normal',
        issue: 'Done',
        kwt: 150,
        note: '',
    },
    {
        sqn: '103',
        name: 'Abdi Hassan',
        phone: '615000003',
        balance: 45.0,
        prevBalance: 10.0,
        total: 55.0,
        fahfahin: 'Cabasho',
        date: '2023-12-22',
        status: 'Unpaid',
        type: 'Redflag',
        issue: 'Solve',
        kwt: 300,
        note: 'Meter issue',
    },
    {
        sqn: '104',
        name: 'Khadra Yusuf',
        phone: '615000004',
        balance: 10.0,
        prevBalance: 0.0,
        total: 10.0,
        fahfahin: 'Discount',
        date: '2023-12-24',
        status: 'Discount',
        type: 'Normal',
        issue: 'Process',
        kwt: 80,
        note: 'Discount approved',
    },
    {
        sqn: '105',
        name: 'Omar Faruq',
        phone: '615000005',
        balance: 5.0,
        prevBalance: 100.0,
        total: 105.0,
        fahfahin: 'Caawa',
        date: '2023-12-25',
        status: 'Pending',
        type: 'Qatato',
        issue: 'Process',
        kwt: 0,
        note: '',
    },
    {
        sqn: '106',
        name: 'Shop A',
        phone: '615000006',
        balance: 100.0,
        prevBalance: 20.0,
        total: 120.0,
        fahfahin: 'Tagid',
        date: '2023-12-26',
        status: 'Pending',
        type: 'Normal',
        issue: 'Process',
        kwt: 500,
        note: 'Will pay tomorrow',
    },
];

export const MOCK_STATS = [
    { name: 'Balan', value: 48, fill: '#3b82f6' },
    { name: 'Caawa', value: 20, fill: '#8b5cf6' },
    { name: 'Duhur', value: 15, fill: '#10b981' },
    { name: 'Raadin', value: 8, fill: '#f59e0b' },
    { name: 'Tagid', value: 5, fill: '#ef4444' },
];

export const MOCK_TEAM = [
    { id: 101, name: 'Ahmed Yasin', role: 'Collector', status: 'Online', battery: 85, lastActive: 'Now', target: 200, paid: 150, zone: 'Waberi', image: '' },
    { id: 102, name: 'Fatima Ali', role: 'Collector', status: 'Online', battery: 42, lastActive: '5m ago', target: 250, paid: 120, zone: 'Hodan', image: '' },
    { id: 103, name: 'Mohamed Nur', role: 'Collector', status: 'Offline', battery: 12, lastActive: '1h ago', target: 180, paid: 180, zone: 'Karaan', image: '' },
    { id: 104, name: 'Khadija Omar', role: 'Collector', status: 'Active', battery: 67, lastActive: 'Now', target: 300, paid: 50, zone: 'Daynile', image: '' },
    { id: 105, name: 'Hassan Geedi', role: 'Collector', status: 'Active', battery: 90, lastActive: '2m ago', target: 220, paid: 200, zone: 'Hamar Weyne', image: '' },
    { id: 106, name: 'Amina Farah', role: 'Collector', status: 'Online', battery: 55, lastActive: '10m ago', target: 190, paid: 45, zone: 'Yaqshid', image: '' },
];

export const MOCK_BAAFIYE_DATA = {
    'Ahmed Yasin': [
        { id: 1001, sqn: '101A01', name: 'Mustafa Cafe', balance: '45.00', status: 'Pending', zone: 'Waberi', lastVisit: '2023-12-24' },
        { id: 1002, sqn: '101A02', name: 'Halima Shop', balance: '0.00', status: 'Paid', zone: 'Waberi', lastVisit: 'Today' },
        { id: 1003, sqn: '101A03', name: 'Waberi Pharmacy', balance: '120.50', status: 'Balan', zone: 'Waberi', lastVisit: '2023-12-20' },
        { id: 1004, sqn: '101A04', name: 'Blue Sky Hotel', balance: '300.00', status: 'Pending', zone: 'Waberi', lastVisit: '2023-12-22' },
        { id: 1005, sqn: '101A05', name: 'Ahmed Gurey School', balance: '0.00', status: 'Paid', zone: 'Waberi', lastVisit: 'Today' },
        { id: 1006, sqn: '101A06', name: 'Family Mart', balance: '15.00', status: 'Pending', zone: 'Waberi', lastVisit: '2023-12-23' },
    ],
    'Fatima Ali': [
        { id: 2001, sqn: '102F01', name: 'Hodan Supermarket', balance: '0.00', status: 'Paid', zone: 'Hodan', lastVisit: 'Today' },
        { id: 2002, sqn: '102F02', name: 'Al-Baraka Restaurant', balance: '55.00', status: 'Pending', zone: 'Hodan', lastVisit: '2023-12-24' },
        { id: 2003, sqn: '102F03', name: 'City Plaza', balance: '0.00', status: 'Paid', zone: 'Hodan', lastVisit: 'Today' },
        { id: 2004, sqn: '102F04', name: 'Salama Hospital', balance: '450.00', status: 'Balan', zone: 'Hodan', lastVisit: '2023-12-21' },
        { id: 2005, sqn: '102F05', name: 'Hodan Gym', balance: '30.00', status: 'Pending', zone: 'Hodan', lastVisit: 'Today' },
    ],
    'Mohamed Nur': [
        { id: 3001, sqn: '103M01', name: 'Karaan Market', balance: '25.00', status: 'Pending', zone: 'Karaan', lastVisit: '2023-12-23' },
        { id: 3002, sqn: '103M02', name: 'Sea View Cafe', balance: '0.00', status: 'Paid', zone: 'Karaan', lastVisit: 'Today' },
    ]
};
