-- 7. Add Subscription Fields to Profiles (Safe to run)
alter table public.profiles 
add column if not exists subscription_expiry timestamptz,
add column if not exists subscription_status text default 'inactive';

-- 10. Create NOTIFICATIONS Table (New)
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  title text not null,
  message text not null,
  read boolean default false,
  type text default 'info', -- 'info', 'warning', 'success', 'error'
  created_at timestamptz default now()
);
alter table public.notifications enable row level security;
-- Drop policies if they exist to avoid errors on re-run
drop policy if exists "Users see own notifications" on notifications;
drop policy if exists "Admins create notifications" on notifications;

create policy "Users see own notifications" on notifications for select using (auth.uid() = user_id);
create policy "Admins create notifications" on notifications for insert with check (auth.role() = 'authenticated');

-- 11. Create APP_SETTINGS Table (New)
create table if not exists public.app_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz default now()
);
alter table public.app_settings enable row level security;
drop policy if exists "Authenticated read settings" on app_settings;
drop policy if exists "Admins manage settings" on app_settings;

create policy "Authenticated read settings" on app_settings for select using (auth.role() = 'authenticated');
create policy "Admins manage settings" on app_settings for all using (auth.role() = 'authenticated');

-- 12. Create TICKETS Table (New)
create table if not exists public.tickets (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id), -- Creator
  customer_sqn text,
  customer_name text,
  status text default 'Pending', -- 'Pending', 'Kiro Suge', 'Unpaid', etc.
  issue text default 'Process', -- 'Process', 'Solve', 'Done'
  note text,
  kwt text,
  assigned_supervisor text, -- Storing name for simplicity as per legacy
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
alter table public.tickets enable row level security;
drop policy if exists "Authenticated read tickets" on tickets;
drop policy if exists "Authenticated manage tickets" on tickets;

create policy "Authenticated read tickets" on tickets for select using (auth.role() = 'authenticated');
create policy "Authenticated manage tickets" on tickets for all using (auth.role() = 'authenticated');

-- Add columns for Baafiye enhancement
alter table public.customers add column if not exists is_favorite boolean default false;
alter table public.customers add column if not exists call_count integer default 0;

-- Update handle_new_user for Pending Status and Metadata
create or replace function public.handle_new_user() 
returns trigger as d:/Beco app/beco-react-app
begin
  insert into public.profiles (id, email, full_name, role, status, phone, district, branch_id)
  values (
    new.id, 
    new.email, 
    new.raw_user_meta_data->>'full_name', 
    coalesce(new.raw_user_meta_data->>'role', 'Collector'),
    'pending', -- Default status is now pending
    new.raw_user_meta_data->>'phone',
    new.raw_user_meta_data->>'zone',
    (new.raw_user_meta_data->>'branch_id')::bigint
  );
  return new;
end;
d:/Beco app/beco-react-app language plpgsql security definer;
