-- 1. Create Branches Table
create table if not exists public.branches (
  id bigint generated by default as identity primary key,
  name text not null unique,
  location text,
  manager_name text,
  manager_phone text,
  status text default 'Active',
  created_at timestamptz default now()
);

-- 2. Insert Default Branches
insert into public.branches (name, location)
values 
  ('WSH', 'WSH'),
  ('DRS', 'DRS'),
  ('DKL', 'DKL'),
  ('MDN', 'MDN'),
  ('KPP', 'KPP')
on conflict (name) do nothing;

-- 3. Ensure Profiles table links to Branches
-- (Assuming profiles table already exists, just checking constraint)
do $$ 
begin
  if not exists (select 1 from information_schema.columns where table_name = 'profiles' and column_name = 'branch_id') then
    alter table public.profiles add column branch_id bigint references public.branches(id);
  end if;
end $$;

-- 4. Enable RLS on Branches
alter table public.branches enable row level security;

-- Policies for Branches
create policy "Public read branches" on branches for select using (true);
create policy "Admins manage branches" on branches for all using (auth.role() = 'authenticated');
